# SPDX-FileCopyrightText: Copyright (C) 2021 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  redis:
      restart: always
      image: redis:7.4.2-alpine3.21
      environment:
        - TZ=America/Toronto
  app:
    restart: always
    build:
      context: .
      args:
        - PHP_ENV=development
    env_file:
      - .env
    expose:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - TZ=America/Toronto
    volumes:
      - .:/var/www/html/
      # don't overwrite existing content in these directories
      # needed if you want to manage these through the Docker image build process only
      - /var/www/html/node_modules
      - /var/www/html/vendor
  nginx:
    # env_file:
    #  - .env
    container_name: nginx
    build:
      context: ./services/nginx
      args:
        NGINX_CONF: nginx_ec2.conf
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge
      - /etc/letsencrypt/live/mycarexadminlegacy.gheit.co/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/mycarexadminlegacy.gheit.co/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - app
  cron:
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - .:/var/www/html/
      - ./logs/opaladmin:/var/www/html/publisher/logs
      # don't overwrite existing content in these directories
      # needed if you want to manage these through the Docker image build process only
      - /var/www/html/node_modules
      - /var/www/html/vendor
    depends_on:
      - app
    # cron needs to run as root
    user: root
    entrypoint: ['/cron.sh']